# Autogenerated wrapper script for Aeron_jll for x86_64-w64-mingw32-cxx03
export aeronmd, aeronmd_s, libaeron

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Aeron")
JLLWrappers.@declare_library_product(libaeron, "libaeron.dll")
JLLWrappers.@declare_executable_product(aeronmd)
JLLWrappers.@declare_executable_product(aeronmd_s)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libaeron,
        "bin\\libaeron.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aeronmd,
        "bin\\aeronmd.exe",
    )

    JLLWrappers.@init_executable_product(
        aeronmd_s,
        "bin\\aeronmd_s.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
