# Autogenerated wrapper script for Aeron_jll for x86_64-w64-mingw32-cxx11
export aeronmd, libaeron, libaeron_archive_c_client, libaeron_driver

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Aeron")
JLLWrappers.@declare_library_product(libaeron, "libaeron.dll")
JLLWrappers.@declare_library_product(libaeron_archive_c_client, "libaeron_archive_c_client.dll")
JLLWrappers.@declare_library_product(libaeron_driver, "libaeron_driver.dll")
JLLWrappers.@declare_executable_product(aeronmd)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libaeron,
        "bin\\libaeron.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaeron_archive_c_client,
        "bin\\libaeron_archive_c_client.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaeron_driver,
        "bin\\libaeron_driver.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aeronmd,
        "bin\\aeronmd_s.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
